name: PR Target Branch Practice

on:
  pull_request:
    branches:
      - main

jobs:
  pr-test:
    runs-on: ubuntu-latest

    steps:
      - name: PR Triggered
        run: echo "Pull Request targeting main triggered"

      - name: Show source branch
        run: echo "Source Branch:${{ github.head_ref }}"

      - name: Show target branch
        run: echo "Target Branch:${{ github.base_ref }}"