name: PR Target Main Practice

on:
  pull_request:
    branches:
      - main

jobs:
  pr-test:
    runs-on: ubuntu-latest

    steps:
      - name: PR Triggered
        run: echo "PR targeting main triggered"
      