name: Pull Request Practice

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request-test:
    runs-on: ubuntu-latest

    steps:
      - name: Show PR message
        run: echo "GitHub Actions ran because a Pull Request was created or updated."

      - name: Show branch information
        run: echo "This workflow is checking changes before merging into main."