name: Manual Practice

on:
  workflow_dispatch:

jobs:
  manual-test:
    runs-on: ubuntu-latest

    steps:
      - name: Show message
        run: echo "I manually started this GitHub Actions workflow!"

      - name: Show date
        run: date