name: Push Event Practice123

on:
  push:
    paths:
      - 'README.md'
      - 'package.json'
      - '.github/workflows/**'
jobs:
  push-test:
    runs-on: ubuntu-latest

    steps:
      - name: Show push message
        run: echo "A push event triggered this workflow."
